name: command
on: workflow_dispatch
jobs:
  command:
    name: Use Linux commands
    runs-on: ubuntu-20.04
    steps:
      - name: show
        run: |
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          rm -rf rsa
          git clone https://github.com/rotarymars/rsa.git
          cd rsa
          ls
      - name: generate
        run: |
          python generate_primenumber.py 10000
      - name: push
        run: |
          git add .
          git commit -m "auto commit"
          git push origin main
          
