name: command
on: 
  schedule:
    - cron: "15 * * * *"
jobs:
  command:
    name: Use Linux commands
    runs-on: ubuntu-20.04
    steps:
      - name: show
        run: pwd
      - name: generate
        run: python generate_primenumbers.py
      - name: push
        run: |
          git add .
          git commit -m "auto commit"
          git push origin main
          
